FROM golang:1.25 AS build
WORKDIR /src
COPY chain-insights-graph-devkit/ ./
RUN go test ./...
RUN go build -o /out/chain-insights-graph-devkit ./cmd/chain-insights-graph-devkit

FROM gcr.io/distroless/base-debian12
COPY --from=build /out/chain-insights-graph-devkit /usr/local/bin/chain-insights-graph-devkit
EXPOSE 8012
ENTRYPOINT ["/usr/local/bin/chain-insights-graph-devkit"]
