import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const root = process.cwd()

function read(path: string): string {
  return readFileSync(join(root, path), 'utf8')
}

function expectNoRetiredHostedMcpHost(content: string): void {
  expect(content).not.toMatch(/(^|[^a-z0-9-])mcp\.chain-insights\.ai(?=\/|[\s`'")\]}]|$)/i)
}

describe('shipped Chain Insights skills contract', () => {
  it('keeps investigation guidance on initialized workspaces and role-specific trace tools', () => {
    const skill = read('skills/chain-insights-investigation/SKILL.md')

    expect(skill).toContain('cia init .')
    expect(skill).toContain('No investigation output belongs under ~/.chain-insights')
    expect(skill).toContain('trace_victim_funds')
    expect(skill).toContain('trace_suspect_funds')
    expect(skill).toContain('trace_deposit_sources')
    expect(skill).toContain('single-address')
    expect(skill).toContain('victim_addresses')
    expect(skill).toContain('Python GraphRAG MCP is the golden behavior')
    expect(skill).toContain('GraphRAGQueryEngine.check_address_risk')
    expect(skill).toContain('graph_query_batch')
    expect(skill).toContain('USE live_topology')
    expect(skill).toContain('USE archive_topology')
    expect(skill).toContain('USE facts')
    expect(skill).toContain('cia mcp networks')
    expect(skill).toContain('Dataset')
    expect(skill).toContain('<first_height>..<last_height> / <first_date>..<last_date>')
    expect(skill).toContain('Available tools')
    expect(skill).toContain('Bittensor contains both native Substrate/SS58')
    expect(skill).toContain('network=bittensor')
    expect(skill).toContain('do not switch networks based only on address')
    expect(skill).toContain('EVM-pallet `0x...`')
    expect(skill).toContain('address_type')
    expect(skill).toContain('Some Graph MCP deployments do not')
    expect(skill).toContain('generated fixed-depth `FLOWS_TO` query batches')
    expect(skill).not.toContain('track_funds')
    expect(skill).not.toContain('scam_topology')
    expect(skill).not.toContain('Use `trace_funds`')
    expect(skill).not.toContain('trace_funds')
  })

  it('documents trace-tool chaining and workspace-local output layout', () => {
    const skill = read('skills/chain-insights-trace-funds/SKILL.md')

    expect(skill).toContain('# Chain Insights Trace Tools')
    expect(skill).toContain('trace_victim_funds')
    expect(skill).toContain('trace_suspect_funds')
    expect(skill).toContain('trace_deposit_sources')
    expect(skill).toContain('chain-insights.trace.v1')
    expect(skill).toContain('label_candidates')
    expect(skill).toContain('Victim/source addresses are not risky labels')
    expect(skill).toContain('single address')
    expect(skill).toContain('reports/graphs/*.graph.json')
    expect(skill).toContain('/graph-reports/<filename>.graph.json')
    expect(skill).toContain('reports/*.graph.html')
    expect(skill).toContain('reports/tables/*.compact-evidence.json')
    expect(skill).toContain('reports/tables/*.flows.csv')
    expect(skill).toContain('reports/*.table.html')
    expect(skill).toContain('reports/*.trace-report.md')
    expect(skill).toContain('No investigation output belongs under `~/.chain-insights`')
    expect(skill).toContain('cia mcp networks')
    expect(skill).toContain('Topology: yes')
    expect(skill).toContain('<first_height>..<last_height> / <first_date>..<last_date>')
    expect(skill).toContain('Python GraphRAG MCP is the golden implementation')
    expect(skill).toContain('StolenFundsProbe')
    expect(skill).toContain('Some Graph MCP deployments do not')
    expect(skill).toContain('generated fixed-depth `FLOWS_TO` query batches')
    expect(skill).not.toContain('track_funds')
    expect(skill).not.toContain('scam_topology')
    expect(skill).not.toContain('trace_funds')
  })

  it('documents role-specific trace chaining and review-only candidate labels', () => {
    const readme = read('README.md')
    const graphToolsDoc = read('docs/graph-tools.md')
    const traceFundsSkill = read('skills/chain-insights-trace-funds/SKILL.md')
    const investigationSkill = read('skills/chain-insights-investigation/SKILL.md')
    const combined = [readme, graphToolsDoc, traceFundsSkill, investigationSkill].join('\n')

    expect(combined).toContain('trace_victim_funds')
    expect(combined).toContain('trace_deposit_sources')
    expect(combined).toContain('trace_suspect_funds')
    expect(combined).toContain('victim/source traversal is outward from victim/source funds')
    expect(combined).toContain('incident_timestamp_ms')
    expect(combined).toContain('exchange terminal safety')
    expect(combined).toContain('reviewable, not automatic writes')
    expect(combined).toContain('cia mcp trace-suspect-funds --network bittensor --suspect-addresses 5... --max-hops 16')
    expect(combined).not.toContain('cia mcp scam-topology')
  })

  it('replaces ci-case and ci-status placeholders with workspace guidance', () => {
    const ciCase = read('skills/ci-case/SKILL.md')
    const ciStatus = read('skills/ci-status/SKILL.md')

    expect(ciCase).toContain('cia init .')
    expect(ciCase).toContain('Cases live under the workspace `cases/` directory')
    expect(ciCase).not.toContain('placeholder')
    expect(ciCase).not.toContain('Phase 3')

    expect(ciStatus).toContain('workspace')
    expect(ciStatus).toContain('The workspace is the investigation root')
    expect(ciStatus).not.toContain('placeholder')
    expect(ciStatus).not.toContain('Config:  /home/user/.chain-insights')
    expect(ciStatus).not.toContain('~/.chain-insights` as')
  })

  it('keeps UAT guidance and scripts from treating home as an investigation output root', () => {
    const skill = read('skills/test-chain-insights-graphrag-mcp/SKILL.md')
    const investigationUat = read('skills/chain-insights-investigation/scripts/run-target-uat.sh')
    const graphragUat = read('skills/test-chain-insights-graphrag-mcp/scripts/run-uat.sh')

    expect(skill).toContain('temporary initialized Chain Insights workspace')
    expect(skill).toContain('chain-insights mcp networks')
    expect(skill).toContain('dataset height/date coverage')
    expect(skill).toContain('~/.chain-insights/reports')
    expect(skill).toContain('~/.chain-insights/cases')
    expect(skill).toContain('CLI graph_query')

    for (const script of [investigationUat, graphragUat]) {
      expect(script).toContain('GLOBAL_REPORTS="${HOME}/.chain-insights/reports"')
      expect(script).toContain('GLOBAL_CASES="${HOME}/.chain-insights/cases"')
      expect(script).toContain('CONFIG_SNAPSHOT_READY=0')
      expect(script).toContain('snapshot_global_outputs')
      expect(script).toContain('assert_no_global_outputs_changed')
      expect(script).toContain('trap finish EXIT')
    }

    expect(graphragUat).toContain('node "${CHAIN_INSIGHTS_CLI}" init "${WORKSPACE_ROOT}" --force')
    expect(graphragUat).toContain('export CHAIN_INSIGHTS_WORKSPACE="${WORKSPACE_ROOT}"')
    expect(graphragUat).toContain('cd "${WORKSPACE_ROOT}"')
    expect(graphragUat).toContain('node "${CHAIN_INSIGHTS_CLI}" debug on --token "${DEBUG_TOKEN}" --endpoint "${MCP_ENDPOINT}"')
    expect(graphragUat).toContain('--cli node "${CHAIN_INSIGHTS_PROXY}"')
    expect(graphragUat).not.toContain('--cli "node ${CHAIN_INSIGHTS_PROXY}"')
    expect(graphragUat).not.toContain('config set mcpEndpoint')
    expect(graphragUat).not.toContain('config set mcpAuthToken')
    expect(investigationUat).toContain('cia case session start "${CASE_ID}"')
    expect(investigationUat).toContain('cia case evidence add "${CASE_ID}"')
    expect(investigationUat).toContain('cia case show "${CASE_ID}"')
    expect(investigationUat).toContain('cia mcp call graph_query_batch')
    expect(investigationUat).toContain('USE live_topology')
  })

  it('requires only current public proxy tools in GraphRAG UAT', () => {
    const script = read('skills/test-chain-insights-graphrag-mcp/scripts/run-uat.sh')
    const proxySection = script.slice(script.indexOf('PROXY_TOOLS_JSON='))

    expect(proxySection).toContain(
      "const required = ['balance', 'help', 'address_risk', 'stake_insights', 'trace_victim_funds', 'trace_suspect_funds', 'trace_deposit_sources', 'network_capabilities', 'graph_query', 'graph_query_batch']",
    )
    expect(proxySection).toContain(
      "for (const hidden of ['topup', 'trace_funds', 'track_funds', 'scam_topology', 'money_flows_between_exchanges', 'address_connection_risk'])",
    )
    expect(proxySection).toContain("for (const name of ['address_risk', 'stake_insights', 'trace_victim_funds', 'trace_suspect_funds', 'trace_deposit_sources'])")
    expect(proxySection).not.toContain("const required = ['balance', 'topup'")
    expect(proxySection).not.toContain("'money_flows_between_exchanges', 'address_connection_risk', 'graph_query']")
    expect(proxySection).not.toContain("for (const name of ['address_risk', 'track_funds', 'money_flows_between_exchanges'")
    expect(script).toContain('node "${CHAIN_INSIGHTS_CLI}" mcp call graph_query')
    expect(script).toContain('USE live_topology MATCH')
  })

  it('keeps README product-first and moves debug/client detail to focused docs', () => {
    const readme = read('README.md')
    const mcpProxy = read('docs/mcp-proxy.md')
    const packageJson = read('package.json')

    expect(readme).toContain('open-source AML investigation toolkit')
    expect(readme).toContain('https://chain-insights.ai')
    expect(readme).toContain('https://github.com/chainswarm/chain-insights')
    expect(readme).toContain('GraphRAG MCP')
    expect(readme).toContain('cia config set graphMcpEndpoint https://staging-mcp.chain-insights.ai/mcp')
    expect(readme).toContain('CHAIN_INSIGHTS_GRAPH_MCP_ENDPOINT=https://staging-mcp.chain-insights.ai/mcp')
    expect(readme).toContain('http://127.0.0.1:8012/mcp')
    expect(readme).toContain('approved access key')
    expect(readme).toContain('prepared wallet')
    expect(readme).toContain('[MCP proxy](docs/mcp-proxy.md)')
    expect(readme).toContain('address_risk')
    expect(readme).toContain('trace_victim_funds')
    expect(readme).toContain('trace_suspect_funds')
    expect(readme).toContain('trace_deposit_sources')
    expect(readme).toContain('graph_query')
    expect(readme).toContain('graph_query_batch')
    expect(readme).toContain('live_topology')
    expect(readme).toContain('archive_topology')
    expect(readme).toContain('facts')
    expect(readme).toContain('cia mcp networks')
    expect(readme).toContain('cia mcp tools --refresh')
    expect(readme).toContain('docs/contributing.md')
    expect(readme).toContain('docs/debugging.md')

    expect(readme).not.toContain('Claude Desktop')
    expect(readme).not.toContain('Go Graph MCP')
    expect(readme).not.toContain('x402')
    expect(readme).not.toContain('Base USDC')
    expect(readme).not.toContain('USDC on Base')
    expect(readme).not.toContain('paid hosted')
    expect(readme).not.toContain('Memgraph')
    expect(readme).not.toContain('StarRocks')
    expect(readme).not.toContain('chain-insights debug on')
    expect(readme).not.toContain('GRAPH_MCP_GO_DEBUG_BYPASS')
    expect(readme).not.toContain('Release rules:')

    expect(packageJson).not.toContain('x402-paid')
    expect(mcpProxy).toContain('https://staging-mcp.chain-insights.ai/mcp')
    expect(mcpProxy).toContain('The endpoint lives in Chain Insights config, not in the MCP client registration.')
    expect(mcpProxy).toContain('Do not')
    expect(mcpProxy).toContain('bake hosted endpoint URLs into MCP client JSON, source code, or workspace')
    expect(mcpProxy).toContain('x402')
    expectNoRetiredHostedMcpHost(readme + mcpProxy + read('docs/architecture.md'))
  })

  it('does not hardcode hosted GraphRAG MCP endpoints in runtime source defaults', () => {
    const runtimeSources = [
      'src/config/mcp-endpoint.ts',
      'src/config/schema.ts',
      'src/config/index.ts',
      'src/workspace/init.ts',
    ].map(read).join('\n')

    expect(runtimeSources).toContain("http://127.0.0.1:8012/mcp")
    expect(runtimeSources).not.toContain('staging-mcp.chain-insights.ai')
    expectNoRetiredHostedMcpHost(runtimeSources)
  })

  it('ships Chain Insights developer experience guidance for AML tool contributors', () => {
    const skill = read('skills/chain-insights-developer-experience/SKILL.md')
    const contributing = read('docs/contributing.md')
    const debugging = read('docs/debugging.md')
    const development = read('docs/development.md')

    expect(skill).toContain('Chain Insights Developer Experience')
    expect(skill).toContain('GraphRAG MCP')
    expect(skill).toContain('AML tool framework')
    expect(skill).toContain('address_risk')
    expect(skill).toContain('trace_victim_funds')
    expect(skill).toContain('trace_suspect_funds')
    expect(skill).toContain('trace_deposit_sources')
    expect(skill).toContain('live_topology')
    expect(skill).toContain('archive_topology')
    expect(skill).toContain('facts')
    expect(skill).toContain('Dogfood from a clean workspace')

    expect(contributing).toContain('Adding AML Tools')
    expect(contributing).toContain('npm run release:check')
    expect(debugging).toContain('GraphRAG MCP')
    expect(debugging).toContain('Inspector')
    expect(development).toContain('docs/contributing.md')
    expect(development).toContain('docs/debugging.md')
  })

  it('ships generic GraphRAG MCP Cypher guidance with layer-aware schema capture', () => {
    const skill = read('skills/chain-insights-cypher/SKILL.md')
    const examples = read('skills/chain-insights-cypher/references/memgraph-examples.md')
    const openai = read('skills/chain-insights-cypher/agents/openai.yaml')
    const graphTools = read('docs/graph-tools.md')
    const mcpProxy = read('docs/mcp-proxy.md')
    const developerSkill = read('skills/chain-insights-developer-experience/SKILL.md')
    const investigationSkill = read('skills/chain-insights-investigation/SKILL.md')

    expect(skill).toContain('graph_query')
    expect(skill).toContain('graph_query_batch')
    expect(skill).toContain('USE live_topology')
    expect(skill).toContain('USE archive_topology')
    expect(skill).toContain('USE facts')
    expect(skill).toContain('GraphRAG MCP does not append')
    expect(skill).toContain('per_query_timeout_seconds=5')
    expect(skill).toContain('Different networks expose different schemas')
    expect(skill).toContain('AddressFeature')
    expect(skill).toContain('AddressLabel')
    expect(skill).toContain('RiskScore')
    expect(skill).toContain('Avoid backend-specific functions such as `keys()`, `labels()`, `type()`')
    expect(skill).toContain('references/memgraph-examples.md')
    expect(skill).toContain('fixed-hop')
    expect(skill).toContain('No raw StarRocks table names')
    expect(examples).toContain('GraphRAG MCP Cypher Examples')
    expect(examples).toContain('Official Memgraph references')
    expect(examples).toContain('Validated against hosted staging on 2026-05-29')
    expect(examples).toContain('Top outflows by amount')
    expect(examples).toContain('CASE WHEN flow.amount_sum')
    expect(examples).toContain('WHERE a.address STARTS WITH')
    expect(examples).toContain('Address-family census')
    expect(examples).toContain('Fixed-Hop Traversal Fallback')
    expect(examples).toContain('*BFS')
    expect(examples).toContain('*WSHORTEST')
    expect(examples).toContain('*ALLSHORTEST')
    expect(examples).toContain('*KSHORTEST')
    expect(examples).toContain('native operators were rejected on staging')
    expect(examples).toContain('per_query_timeout_seconds=5')
    expect(examples).not.toContain('CREATE (')
    expect(examples).not.toContain('DETACH DELETE')
    expect(openai).toContain('Chain Insights Cypher')
    expect(graphTools).toContain('chain-insights-cypher')
    expect(graphTools).toContain('references/memgraph-examples.md')
    expect(graphTools).toContain('fixed-hop traversal fallbacks')
    expect(mcpProxy).toContain('chain-insights-cypher')
    expect(mcpProxy).toContain('Memgraph examples reference')
    expect(developerSkill).toContain('chain-insights-cypher')
    expect(investigationSkill).toContain('chain-insights-cypher')
  })

  it('ships Bittensor-specific Cypher schema guidance for the combined investigation network', () => {
    const skill = read('skills/chain-insights-bittensor-cypher/SKILL.md')
    const openai = read('skills/chain-insights-bittensor-cypher/agents/openai.yaml')
    const readme = read('README.md')
    const graphTools = read('docs/graph-tools.md')
    const mcpProxy = read('docs/mcp-proxy.md')

    expect(skill).toContain('network=bittensor')
    expect(skill).toContain('native Substrate/SS58')
    expect(skill).toContain('EVM-pallet `0x...`')
    expect(skill).toContain('Do not switch networks just because an address is `0x...`')
    expect(skill).toContain('legacy `bittensor_evm`')
    expect(skill).toContain('address_type')
    expect(skill).toContain('STAKES_IN')
    expect(skill).toContain('TopologySnapshot')
    expect(skill).toContain('REGISTERED_NEURON')
    expect(skill).toContain('SERVED_FROM')
    expect(skill).toContain('Observed against staging on 2026-05-29')
    expect(skill).toContain('WHERE STARTS WITH')
    expect(skill).toContain('address-family counts')
    expect(skill).toContain('references/memgraph-examples.md')
    expect(skill).toContain('native Memgraph deep traversal')
    expect(skill).toContain('archive StarRocks-backed numeric fields')
    expect(skill).toContain('Avoid `keys()`, `labels()`, `type()`')
    expect(openai).toContain('Bittensor Cypher')
    expect(readme).toContain('chain-insights-bittensor-cypher')
    expect(graphTools).toContain('chain-insights-bittensor-cypher')
    expect(mcpProxy).toContain('chain-insights-bittensor-cypher')
  })
})
