import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const root = process.cwd()

function read(path: string): string {
  return readFileSync(join(root, path), 'utf8')
}

function expectNoRetiredHostedMcpHost(content: string): void {
  expect(content).not.toMatch(/(^|[^a-z0-9-])mcp\.chain-insights\.ai(?=\/|[\s`'")\]}]|$)/i)
}

function retiredName(head: string, tail: string): string {
  return `${head}${tail}`
}

describe('shipped Chain Insights skills contract', () => {
  it('keeps investigation guidance on initialized workspaces and role-specific trace tools', () => {
    const skill = read('skills/chain-insights-investigation/SKILL.md')

    expect(skill).toContain('cia init .')
    expect(skill).toContain('No investigation output belongs under ~/.chain-insights')
    expect(skill).toContain('aml_trace_victim_funds')
    expect(skill).toContain('aml_trace_suspect_funds')
    expect(skill).toContain('aml_trace_deposit_sources')
    expect(skill).toContain('single-address')
    expect(skill).toContain('victim_addresses')
    expect(skill).toContain('Python GraphRAG MCP is the golden behavior')
    expect(skill).toContain('GraphRAGQueryEngine.check_aml_address_risk')
    expect(skill).toContain('graph_query_batch')
    expect(skill).toContain('USE live_topology')
    expect(skill).toContain('USE archive_topology')
    expect(skill).toContain('USE facts')
    expect(skill).toContain('cia mcp networks')
    expect(skill).toContain('Dataset')
    expect(skill).toContain('<first_height>..<last_height> / <first_date>..<last_date>')
    expect(skill).toContain('Available tools')
    expect(skill).toContain('Bittensor contains both native Substrate/SS58')
    expect(skill).toContain('network=bittensor')
    expect(skill).toContain('do not switch networks based only on address')
    expect(skill).toContain('EVM-pallet `0x...`')
    expect(skill).toContain('address_type')
    expect(skill).toContain('Some Graph MCP deployments do not')
    expect(skill).toContain('generated fixed-depth `FLOWS_TO` query batches')
    expect(skill).toContain('exchange hot wallets are terminal endpoints only')
    expect(skill).toContain('chain-insights.evidence_pointer.v1')
    expect(skill).toContain('LLM Wiki')
    expect(skill).not.toContain(retiredName('track', '_funds'))
    expect(skill).not.toContain(retiredName('scam', '_topology'))
    expect(skill).not.toContain(`Use \`${retiredName('trace', '_funds')}\``)
    expect(skill).not.toContain(retiredName('trace', '_funds'))
  })

  it('documents trace-tool chaining and workspace-local output layout', () => {
    const skill = read('skills/chain-insights-trace-funds/SKILL.md')

    expect(skill).toContain('# Chain Insights Trace Tools')
    expect(skill).toContain('aml_trace_victim_funds')
    expect(skill).toContain('aml_trace_suspect_funds')
    expect(skill).toContain('aml_trace_deposit_sources')
    expect(skill).toContain('chain-insights.trace.v1')
    expect(skill).toContain('label_candidates')
    expect(skill).toContain('Victim/source addresses are not risky labels')
    expect(skill).toContain('single address')
    expect(skill).toContain('reports/graphs/*.graph.json')
    expect(skill).toContain('/graph-reports/<filename>.graph.json')
    expect(skill).toContain('reports/*.graph.html')
    expect(skill).toContain('reports/tables/*.compact-evidence.json')
    expect(skill).toContain('reports/tables/*.flows.csv')
    expect(skill).toContain('reports/*.table.html')
    expect(skill).toContain('reports/*.trace-report.md')
    expect(skill).toContain('No investigation output belongs under `~/.chain-insights`')
    expect(skill).toContain('cia mcp networks')
    expect(skill).toContain('Topology: yes')
    expect(skill).toContain('<first_height>..<last_height> / <first_date>..<last_date>')
    expect(skill).toContain('Python GraphRAG MCP is the golden implementation')
    expect(skill).toContain('StolenFundsProbe')
    expect(skill).toContain('Some Graph MCP deployments do not')
    expect(skill).toContain('generated fixed-depth `FLOWS_TO` query batches')
    expect(skill).toContain('exchange hot wallets are terminal')
    expect(skill).not.toContain(retiredName('track', '_funds'))
    expect(skill).not.toContain(retiredName('scam', '_topology'))
    expect(skill).not.toContain(retiredName('trace', '_funds'))
    expect(skill).not.toContain('--case')
  })

  it('ships dedicated address-risk and exposure-analysis skills with current contracts', () => {
    const addressRisk = read('skills/chain-insights-address-risk/SKILL.md')
    const exposure = read('skills/chain-insights-exposure-analysis/SKILL.md')

    expect(addressRisk).toContain('aml_address_risk')
    expect(addressRisk).toContain('single-address AML screening')
    expect(addressRisk).toContain('compare_address')
    expect(addressRisk).toContain('reports/graphs/')
    expect(addressRisk).toContain('reports/tables/')
    expect(addressRisk).toContain('Markdown summary/report files under `reports/`')
    expect(addressRisk).toContain('No investigation output belongs under `~/.chain-insights`')
    expect(addressRisk).not.toContain(retiredName('trace', '_funds'))

    expect(exposure).toContain('exposure_profile')
    expect(exposure).toContain('exposure_quality')
    expect(exposure).toContain('exposure_carry')
    expect(exposure).toContain('exposure_crowding')
    expect(exposure).toContain('exposure_exit_pressure')
    expect(exposure).toContain('exposure_correlation')
    expect(exposure).toContain('exposure_explain')
    expect(exposure).toContain('summaryText')
    expect(exposure).toContain('structuredContent')
    expect(exposure).toContain('reports/')
    expect(exposure).toContain('reports/tables/')
    expect(exposure).toContain('graph HTML')
    expect(exposure).toContain('graph JSON visualization bundles')
    expect(exposure).not.toContain('aml_trace_victim_funds')
  })

  it('documents role-specific trace chaining and review-only candidate labels', () => {
    const readme = read('README.md')
    const graphToolsDoc = read('docs/graph-tools.md')
    const traceFundsSkill = read('skills/chain-insights-trace-funds/SKILL.md')
    const investigationSkill = read('skills/chain-insights-investigation/SKILL.md')
    const combined = [readme, graphToolsDoc, traceFundsSkill, investigationSkill].join('\n')

    expect(combined).toContain('aml_trace_victim_funds')
    expect(combined).toContain('aml_trace_deposit_sources')
    expect(combined).toContain('aml_trace_suspect_funds')
    expect(combined).toContain('victim/source traversal is outward from victim/source funds')
    expect(combined).toContain('incident_timestamp_ms')
    expect(combined).toContain('exchange terminal safety')
    expect(combined).toContain('penultimate non-exchange')
    expect(combined).toContain('reviewable, not automatic writes')
    expect(combined).toContain('cia mcp trace-suspect-funds --network bittensor --suspect-addresses 5... --max-hops 16')
    expect(combined).not.toContain('cia mcp scam-topology')
  })

  it('keeps ci-status on workspace guidance without legacy case commands', () => {
    const ciStatus = read('skills/ci-status/SKILL.md')

    expect(ciStatus).toContain('workspace')
    expect(ciStatus).toContain('The workspace is the investigation root')
    expect(ciStatus).toContain('Artifacts:')
    expect(ciStatus).not.toContain('placeholder')
    expect(ciStatus).not.toContain('Config:  /home/user/.chain-insights')
    expect(ciStatus).not.toContain('~/.chain-insights` as')
    expect(ciStatus).not.toContain('cia case list')
  })

  it('keeps UAT guidance and scripts from treating home as an investigation output root', () => {
    const skill = read('skills/test-chain-insights-graphrag-mcp/SKILL.md')
    const investigationUat = read('skills/chain-insights-investigation/scripts/run-target-uat.sh')
    const graphragUat = read('skills/test-chain-insights-graphrag-mcp/scripts/run-uat.sh')

    expect(skill).toContain('temporary initialized Chain Insights workspace')
    expect(skill).toContain('chain-insights mcp networks')
    expect(skill).toContain('dataset height/date coverage')
    expect(skill).toContain('topology_scope=identity')
    expect(skill).toContain('facts.routing.starrocks_database=bittensor_semantic')
    expect(skill).not.toContain('network=bittensor_identity')
    expect(skill).toContain('~/.chain-insights/reports')
    expect(skill).toContain('CLI graph_query')
    expect(skill).toContain('do not return `_meta.chainInsights.graph`')
    expect(skill).toContain('persist readable outputs under `reports/` and `reports/tables/`')

    for (const script of [investigationUat, graphragUat]) {
      expect(script).toContain('GLOBAL_REPORTS="${HOME}/.chain-insights/reports"')
      expect(script).toContain('CONFIG_SNAPSHOT_READY=0')
      expect(script).toContain('snapshot_global_outputs')
      expect(script).toContain('assert_no_global_outputs_changed')
      expect(script).toContain('trap finish EXIT')
    }

    expect(graphragUat).toContain('node "${CHAIN_INSIGHTS_CLI}" init "${WORKSPACE_ROOT}" --force')
    expect(graphragUat).toContain('export CHAIN_INSIGHTS_WORKSPACE="${WORKSPACE_ROOT}"')
    expect(graphragUat).toContain('cd "${WORKSPACE_ROOT}"')
    expect(graphragUat).toContain('node "${CHAIN_INSIGHTS_CLI}" debug on --token "${DEBUG_TOKEN}" --endpoint "${MCP_ENDPOINT}"')
    expect(graphragUat).toContain('--cli node "${CHAIN_INSIGHTS_PROXY}"')
    expect(graphragUat).not.toContain('--cli "node ${CHAIN_INSIGHTS_PROXY}"')
    expect(graphragUat).not.toContain('config set mcpEndpoint')
    expect(graphragUat).not.toContain('config set mcpAuthToken')
    expect(graphragUat).toContain('returned forbidden graph metadata')
    expect(graphragUat).toContain('checking exposure persistence contract')
    expect(investigationUat).toContain('GLOBAL_ARTIFACTS="${HOME}/.chain-insights/artifacts"')
    expect(investigationUat).toContain('reports/tables/address_exists.compact.json')
    expect(investigationUat).toContain('entities/${TARGET_ADDRESS}.md')
    expect(investigationUat).toContain('cia mcp call graph_query_batch')
    expect(investigationUat).toContain('if [[ -d cases || -d Evidence ]]; then')
    expect(investigationUat).not.toContain('cia case ')
  })

  it('requires only current public proxy tools in GraphRAG UAT', () => {
    const script = read('skills/test-chain-insights-graphrag-mcp/scripts/run-uat.sh')
    const proxySection = script.slice(script.indexOf('PROXY_TOOLS_JSON='))

    expect(proxySection).toContain(
      "const required = ['balance', 'help', 'aml_address_risk', 'exposure_profile', 'exposure_quality', 'exposure_carry', 'exposure_crowding', 'exposure_exit_pressure', 'exposure_correlation', 'exposure_explain', 'aml_trace_victim_funds', 'aml_trace_suspect_funds', 'aml_trace_deposit_sources', 'network_capabilities', 'graph_query', 'graph_query_batch', 'usage_status']",
    )
    expect(proxySection).toContain('proxy tools/list exposed unexpected tools')
    expect(proxySection).toContain("for (const name of ['aml_address_risk', 'exposure_profile', 'exposure_quality', 'exposure_carry', 'exposure_crowding', 'exposure_exit_pressure', 'exposure_correlation', 'exposure_explain', 'aml_trace_victim_funds', 'aml_trace_suspect_funds', 'aml_trace_deposit_sources'])")
    expect(proxySection).not.toContain("const required = ['balance', 'topup'")
    expect(proxySection).toContain('names.size !== required.length')
    expect(script).toContain('node "${CHAIN_INSIGHTS_CLI}" mcp call graph_query')
    expect(script).toContain('USE live_topology MATCH')
    expect(script).not.toContain('IDENTITY_NETWORK')
    expect(script).not.toContain('bittensor_identity')
    expect(script).toContain('direct-network-capabilities.json')
    expect(script).toContain('checking semantic identity network capabilities')
    expect(script).toContain('direct-identity-topology.json')
    expect(script).toContain('--tool-arg "topology_scope=identity"')
    expect(script).toContain('checking public-route identity topology')
    expect(script).toContain('public-route identity topology ok')
    expect(script).toContain('direct-semantic-facts.json')
    expect(script).toContain('UAT_IDENTITY_KEY="${UAT_IDENTITY_KEY:-bittensor:0x')
    expect(script).toContain('checking semantic identity facts query')
    expect(script).toContain('semantic facts query ok')
    expect(script).toContain('direct-address-topology.json')
    expect(script).toContain('checking address topology unregression')
    expect(script).toContain('address topology unregressed')
    expect(script).toContain('UAT_EXPOSURE_ACCOUNT="${UAT_EXPOSURE_ACCOUNT:-}"')
    expect(script).toContain('EXPOSURE_ACCOUNT="${UAT_EXPOSURE_ACCOUNT}"')
    expect(script).toContain('using generic exposure UAT account')
  })

  it('keeps README product-first and moves debug/client detail to focused docs', () => {
    const readme = read('README.md')
    const mcpProxy = read('docs/mcp-proxy.md')
    const packageJson = read('package.json')

    expect(readme).toContain('open-source AML investigation toolkit')
    expect(readme).toContain('https://chain-insights.ai')
    expect(readme).toContain('https://github.com/chainswarm/chain-insights')
    expect(readme).toContain('GraphRAG MCP')
    expect(readme).toContain('cia config set graphMcpEndpoint https://staging-mcp.chain-insights.ai/mcp')
    expect(readme).toContain('CHAIN_INSIGHTS_GRAPH_MCP_ENDPOINT=https://staging-mcp.chain-insights.ai/mcp')
    expect(readme).toContain('http://127.0.0.1:8012/mcp')
    expect(readme).toContain('approved access key')
    expect(readme).toContain('prepared wallet')
    expect(readme).toContain('[MCP proxy](docs/mcp-proxy.md)')
    expect(readme).toContain('aml_address_risk')
    expect(readme).toContain('aml_trace_victim_funds')
    expect(readme).toContain('aml_trace_suspect_funds')
    expect(readme).toContain('aml_trace_deposit_sources')
    expect(readme).toContain('graph_query')
    expect(readme).toContain('graph_query_batch')
    expect(readme).toContain('live_topology')
    expect(readme).toContain('archive_topology')
    expect(readme).toContain('facts')
    expect(readme).toContain('cia mcp networks')
    expect(readme).toContain('cia mcp tools --refresh')
    expect(readme).toContain('published/<workspace-slug>/')
    expect(readme).toContain('docs/contributing.md')
    expect(readme).toContain('docs/debugging.md')

    expect(readme).not.toContain('Claude Desktop')
    expect(readme).not.toContain('Go Graph MCP')
    expect(readme).not.toContain('x402')
    expect(readme).not.toContain('Base USDC')
    expect(readme).not.toContain('USDC on Base')
    expect(readme).not.toContain('paid hosted')
    expect(readme).not.toContain('Memgraph')
    expect(readme).not.toContain('StarRocks')
    expect(readme).not.toContain('chain-insights debug on')
    expect(readme).not.toContain('GRAPH_MCP_GO_DEBUG_BYPASS')
    expect(readme).not.toContain('Release rules:')

    expect(packageJson).not.toContain('x402-paid')
    expect(mcpProxy).toContain('https://staging-mcp.chain-insights.ai/mcp')
    expect(mcpProxy).toContain('The endpoint lives in Chain Insights config, not in the MCP client registration.')
    expect(mcpProxy).toContain('Do not')
    expect(mcpProxy).toContain('bake hosted endpoint URLs into MCP client JSON, source code, or workspace')
    expect(mcpProxy).toContain('x402')
    expectNoRetiredHostedMcpHost(readme + mcpProxy + read('docs/architecture.md'))
  })

  it('positions Chain Insights as an editor-neutral workspace', () => {
    const readme = read('README.md')
    const investigation = read('docs/investigation-workspaces.md')
    const mcpProxy = read('docs/mcp-proxy.md')
    const graphTools = read('docs/graph-tools.md')

    expect(readme).toContain('Create an investigation workspace')
    expect(readme).not.toContain('obsidian')
    expect(readme).not.toMatch(/open as\s+(?:a\s+)?vault/i)

    for (const content of [investigation, mcpProxy, graphTools]) {
      expect(content.toLowerCase()).not.toContain('obsidian')
      expect(content).not.toMatch(/open as\s+(?:a\s+)?vault/i)
    }
  })

  it('documents workspace-local published outputs instead of external vault/export workflows', () => {
    const readme = read('README.md')
    const graphTools = read('docs/graph-tools.md')
    const investigation = read('docs/investigation-workspaces.md')
    const mcpProxy = read('docs/mcp-proxy.md')

    for (const content of [readme, graphTools, investigation, mcpProxy]) {
      expect(content).toContain('published/')
      expect(content.toLowerCase()).not.toContain('obsidian')
      expect(content).not.toMatch(/open as\s+(?:a\s+)?vault/i)
    }
  })

  it('does not hardcode hosted GraphRAG MCP endpoints in runtime source defaults', () => {
    const runtimeSources = [
      'src/config/mcp-endpoint.ts',
      'src/config/schema.ts',
      'src/config/index.ts',
      'src/workspace/init.ts',
    ].map(read).join('\n')

    expect(runtimeSources).toContain("http://127.0.0.1:8012/mcp")
    expect(runtimeSources).not.toContain('staging-mcp.chain-insights.ai')
    expectNoRetiredHostedMcpHost(runtimeSources)
  })

  it('ships Chain Insights developer experience guidance for AML tool contributors', () => {
    const skill = read('skills/chain-insights-developer-experience/SKILL.md')
    const contributing = read('docs/contributing.md')
    const debugging = read('docs/debugging.md')
    const development = read('docs/development.md')

    expect(skill).toContain('Chain Insights Developer Experience')
    expect(skill).toContain('GraphRAG MCP')
    expect(skill).toContain('AML tool framework')
    expect(skill).toContain('aml_address_risk')
    expect(skill).toContain('aml_trace_victim_funds')
    expect(skill).toContain('aml_trace_suspect_funds')
    expect(skill).toContain('aml_trace_deposit_sources')
    expect(skill).toContain('live_topology')
    expect(skill).toContain('archive_topology')
    expect(skill).toContain('facts')
    expect(skill).toContain('Dogfood from a clean workspace')
    expect(skill).toContain('workspace artifacts')
    expect(skill).not.toContain('obsidian-llmwiki')
    expect(skill).not.toContain('manifest.chain-insights.json')

    expect(contributing).toContain('Adding AML Tools')
    expect(contributing).toContain('Workspace artifact and report behavior.')
    expect(contributing).toContain('npm run release:check')
    expect(debugging).toContain('GraphRAG MCP')
    expect(debugging).toContain('Inspector')
    expect(development).toContain('docs/contributing.md')
    expect(development).toContain('docs/debugging.md')
  })

  it('ships generic GraphRAG MCP Cypher guidance with layer-aware schema capture', () => {
    const skill = read('skills/chain-insights-cypher/SKILL.md')
    const examples = read('skills/chain-insights-cypher/references/memgraph-examples.md')
    const openai = read('skills/chain-insights-cypher/agents/openai.yaml')
    const graphTools = read('docs/graph-tools.md')
    const mcpProxy = read('docs/mcp-proxy.md')
    const developerSkill = read('skills/chain-insights-developer-experience/SKILL.md')
    const investigationSkill = read('skills/chain-insights-investigation/SKILL.md')

    expect(skill).toContain('graph_query')
    expect(skill).toContain('graph_query_batch')
    expect(skill).toContain('USE live_topology')
    expect(skill).toContain('USE archive_topology')
    expect(skill).toContain('USE facts')
    expect(skill).toContain('GraphRAG MCP does not append')
    expect(skill).toContain('per_query_timeout_seconds=5')
    expect(skill).toContain('Different networks expose different schemas')
    expect(skill).toContain('AddressFeature')
    expect(skill).toContain('AddressLabel')
    expect(skill).toContain('RiskScore')
    expect(skill).toContain('Avoid backend-specific functions such as `keys()`, `labels()`, `type()`')
    expect(skill).toContain('references/memgraph-examples.md')
    expect(skill).toContain('fixed-hop')
    expect(skill).toContain('exchange hot wallets are terminal endpoints only')
    expect(skill).toContain('No raw StarRocks table names')
    expect(examples).toContain('GraphRAG MCP Cypher Examples')
    expect(examples).toContain('Official Memgraph references')
    expect(examples).toContain('Validated against hosted staging on 2026-05-29')
    expect(examples).toContain('Top outflows by amount')
    expect(examples).toContain('CASE WHEN flow.amount_sum')
    expect(examples).toContain('WHERE a.address STARTS WITH')
    expect(examples).toContain('Address-family census')
    expect(examples).toContain('Fixed-Hop Traversal Fallback')
    expect(examples).toContain('*BFS')
    expect(examples).toContain('*WSHORTEST')
    expect(examples).toContain('*ALLSHORTEST')
    expect(examples).toContain('*KSHORTEST')
    expect(examples).toContain('native operators were rejected on staging')
    expect(examples).toContain('per_query_timeout_seconds=5')
    expect(examples).not.toContain('CREATE (')
    expect(examples).not.toContain('DETACH DELETE')
    expect(openai).toContain('Chain Insights Cypher')
    expect(graphTools).toContain('chain-insights-cypher')
    expect(graphTools).toContain('references/memgraph-examples.md')
    expect(graphTools).toContain('fixed-hop traversal fallbacks')
    expect(mcpProxy).toContain('chain-insights-cypher')
    expect(mcpProxy).toContain('Memgraph examples reference')
    expect(developerSkill).toContain('chain-insights-cypher')
    expect(investigationSkill).toContain('chain-insights-cypher')
  })

  it('ships Bittensor-specific Cypher schema guidance for the combined investigation network', () => {
    const skill = read('skills/chain-insights-bittensor-cypher/SKILL.md')
    const openai = read('skills/chain-insights-bittensor-cypher/agents/openai.yaml')
    const readme = read('README.md')
    const graphTools = read('docs/graph-tools.md')
    const mcpProxy = read('docs/mcp-proxy.md')

    expect(skill).toContain('network=bittensor')
    expect(skill).toContain('native Substrate/SS58')
    expect(skill).toContain('EVM-pallet `0x...`')
    expect(skill).toContain('Do not switch networks just because an address is `0x...`')
    expect(skill).toContain('legacy `bittensor_evm`')
    expect(skill).toContain('address_type')
    expect(skill).toContain('TopologySnapshot')
    expect(skill).toContain('REGISTERED_NEURON')
    expect(skill).toContain('SERVED_FROM')
    expect(skill).toContain('Observed against staging on 2026-05-29')
    expect(skill).toContain('WHERE STARTS WITH')
    expect(skill).toContain('address-family counts')
    expect(skill).toContain('references/memgraph-examples.md')
    expect(skill).toContain('native Memgraph deep traversal')
    expect(skill).toContain('archive StarRocks-backed numeric fields')
    expect(skill).toContain('Avoid `keys()`, `labels()`, `type()`')
    expect(openai).toContain('Bittensor Cypher')
    expect(readme).toContain('chain-insights-bittensor-cypher')
    expect(graphTools).toContain('chain-insights-bittensor-cypher')
    expect(mcpProxy).toContain('chain-insights-bittensor-cypher')
  })
})
